sudo: required
services:
  - docker

before_install:
  - docker build -t calvinisa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true calvinisa/react-test npm test

after_success:
  - docker build -t calvinisa/multi-client ./client
  - docker build -t calvinisa/multi-nginx ./nginx
  - docker build -t calvinisa/multi-server ./server
  - docker build -t calvinisa/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push calvinisa/multi-client
  - docker push calvinisa/multi-nginx
  - docker push calvinisa/multi-server
  - docker push calvinisa/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: eu-west-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket-name: elasticbeanstalk-eu-west-2-265606896359
#   bucket-path: docker-multi
#   on:
#     branch: master
#   access_key_id: 
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY



